name: Deploy Microservices Demo on GCP

on:
  workflow_dispatch: # Enables manual trigger from GitHub Actions UI

jobs:
  terraform-deploy:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Clean up GCP Credentials
      if: always()
      run: rm -f /tmp/gcp-key.json

    - name: Configure GCP Credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > /tmp/gcp-key.json

    - name: Verify GCP Key File #remember to remove this one
      run: cat /tmp/gcp-key.json

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8 # Specify your Terraform version here

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Plan Terraform Changes
      run: terraform plan -var="gcp_project_id=${{ secrets.GCP_PROJECT }}" -out=tfplan
      working-directory: terraform

    - name: Apply Terraform Changes
      if: github.event.inputs.approve == 'true' # Conditional execution
      run: terraform apply -var="gcp_project_id=${{ secrets.GCP_PROJECT }}" -auto-approve tfplan
      working-directory: terraform

    